env:
  browser: true
  es6: true
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-empty-function:
    - warn
    - allow:
        - arrowFunctions
